### ISSUE TITLE
Add the ability to construct a blob with existing C data

### ISSUE THREAD

**Issue by Wizzard033** [megagrump/blob#1]
In Blob:init(data, size, options), data must be nil or a Lua string
To better perform less copies, I'd like to feed it a C pointer to a buffer
```
local data = ffi.new('uint8_t[256]')
socket:recv(data)

local blob = Blob(data, 256, { source_endianess = "le", target_endianess = "le" })
local num = blob:readU8()
```
Without this feature, 2 interim buffers are created (one by ffi.string, one by blob's init method)

**Comment by megagrump** [comment]
Added support for user supplied cdata in constructor.

**Comment by Wizzard033** [comment]
Thanks!
